export const languageStorageKey = 'lumen-language-v1'

export const serviceMeta = [
  ['poster-design', 'lilac'],
  ['brand-identity', 'ink'],
  ['video-editing', 'charcoal'],
  ['illustration', 'mist'],
  ['live2d', 'violet'],
]

export const projectMeta = [
  ['bloom-festival', 'poster-art', 'BLOOM\nFESTIVAL'],
  ['nura-studio', 'brand-art', 'nura'],
  ['quiet-hours', 'illustration-art', 'quiet\nhours'],
  ['wander-travel-edit', 'motion-art', 'WANDER'],
  ['liora-live2d', 'live2d-art', 'LIORA'],
]

const en = {
  locale: 'en', htmlLang: 'en', pageTitle: 'Lumen Atelier — Design Studio',
  metaDescription: 'Lumen Atelier — branding, posters, motion, illustration and Live2D.',
  brandSubtitle: 'DESIGN STUDIO', brandHomeLabel: 'Lumen Atelier home', navLabel: 'Main navigation', menuLabel: 'Toggle navigation', languageLabel: 'Choose language',
  nav: [['Home','#/'],['Work','#/work'],['Services','#/services'],['About','#/about'],['Contact','#/contact']],
  labels: { startProject:'Start a project', backHome:'Back home', moreAbout:'More about', allServices:'All services', allWork:'All work', serviceDetail:'Service detail', askService:'Ask about this service', goodFor:'A good fit for', deliverables:'Typical deliverables', overview:'Overview', services:'Services', challenge:'The challenge', direction:'Creative direction' },
  services: [
    {title:'Poster Design', intro:'Bold, clear, and made to be seen.', description:'Campaign posters and social visuals with a strong hierarchy, an intentional mood, and a layout that stays clear on every screen.', goodFor:['Campaign launches','Events and promotions','Social media series'], deliverables:['Key visual direction','Final poster artwork','Platform-ready exports','Two refinement rounds']},
    {title:'Brand Identity', intro:'Distinct identities that feel like you.', description:'A thoughtful visual system that gives your business a recognisable voice, from the main mark to colours, type, and everyday applications.', goodFor:['New creative businesses','Brand refreshes','Personal brands'], deliverables:['Creative direction','Logo suite','Colour and type system','Mini brand guide']},
    {title:'Video Editing', intro:'Clean edits that move your story.', description:'Short-form edits shaped around pace, message, and music, with clean typography and movement that supports the story.', goodFor:['Product reels','Campaign teasers','Creator content'], deliverables:['Edit and pacing','Basic motion graphics','Sound polish','Platform-ready export']},
    {title:'Illustration', intro:'Expressive art for brands and people.', description:'Custom illustration with a warm, human touch, developed to fit your story rather than looking like a generic asset.', goodFor:['Editorial artwork','Brand characters','Personal commissions'], deliverables:['Sketch exploration','Colour direction','Final illustration','Web and print exports']},
    {title:'Live2D', intro:'Bringing characters gently to life.', description:'Character preparation and expressive Live2D work designed to feel natural, readable, and full of personality on screen.', goodFor:['VTuber models','Mascot animation','Streaming assets'], deliverables:['Layer review','Rigging plan','Core expressions','Ready-to-use files']},
  ],
  projects: [
    {category:'Poster Design',title:'Bloom Festival',year:'Template case · 2026',overview:'A bright campaign direction for an imagined creative festival, built around generous type, soft colour, and a clear event hierarchy.',challenge:'Create a poster system that feels playful from a distance while keeping dates, venue information, and calls to action easy to scan.',direction:'A lavender-led palette, oversized typography, and modular layouts make the concept easy to adapt across story, feed, and print formats.',services:['Art direction','Poster design','Social adaptations']},
    {category:'Brand Identity',title:'Nura Studio',year:'Template case · 2026',overview:'A quiet identity concept for a modern lifestyle studio, pairing a restrained wordmark with tactile, editorial applications.',challenge:'Build a visual identity that feels calm and premium without becoming distant or too minimal to recognise.',direction:'Warm neutrals, a confident serif detail, and a compact typographic system give the brand softness and consistency.',services:['Identity direction','Logo system','Brand applications']},
    {category:'Illustration',title:'Quiet Hours',year:'Template case · 2026',overview:'A gentle illustration series about slow evenings, private rituals, and the small details that make a space feel like home.',challenge:'Keep the series expressive and personal while using a repeatable visual language that works across multiple scenes.',direction:'Soft shapes, limited colour, and small hand-drawn details create a calm visual rhythm from piece to piece.',services:['Concept sketches','Illustration system','Final artwork']},
    {category:'Video Editing',title:'Wander — Travel Edit',year:'Template case · 2026',overview:'A short travel-film concept that moves between quiet observation and energetic cuts without losing a cohesive mood.',challenge:'Shape mixed footage into a concise story that feels cinematic while still working as fast social content.',direction:'Rhythmic transitions, restrained captions, and a soft tonal grade hold the sequence together.',services:['Story edit','Motion type','Sound and delivery']},
    {category:'Live2D',title:'Liora — VTuber Model',year:'Template case · 2026',overview:'A character-motion template focused on subtle expression, clean silhouette changes, and a friendly on-screen presence.',challenge:'Give the character enough movement to feel alive without distracting from speech or making the rig feel overly elastic.',direction:'Small breathing motion, balanced head angles, and a concise expression set create a natural everyday performance.',services:['Layer planning','Core rigging','Expression setup']},
  ],
  home:{eyebrow:'Independent design studio',heroTitle:['Ideas,','made','visible.'],heroText:'Branding, posters, motion and illustration — thoughtfully made for stories worth noticing.',viewWork:'View selected work',exploreServices:'Explore services',whatWeDo:'What we do',servicesTitle:'Services',viewServices:'View all services',meetStudio:'Meet the studio',studioTitle:['Small studio.','Bright ideas.'],studioText:['Lumen Atelier is a small, multidisciplinary online design studio for creative businesses, personal brands, streamers, and curious people.','We blend strategy, storytelling, and craft to create visuals that connect and leave a lasting impression.'],moreAboutUs:'More about us',notes:[['make it','meaningful'],['sketch','explore','refine']],firstLook:'A first look',selectedWork:'Selected work',viewAllWork:'View all work',templateNote:'These are working case-study templates. Your real projects can replace them without changing the website structure.'},
  servicesPage:{eyebrow:'Services',title:'Creative support, shaped around your story.',text:'Choose a starting point below. Every service has its own detail page, deliverables, and a clear route back home.',flexible:'Flexible by design',moreThanOne:'Need more than one service?',packageText:'Branding can flow into posters. Illustration can become motion. A Live2D model may need launch visuals. Tell us what the project needs and we can shape a joined-up package.',packageButton:'Build a custom project',howItWorks:'How it works',stepsTitle:'Clear steps, thoughtful decisions.',stepsText:'We begin with your goals and references, then establish a visual direction before refining the final work. The exact timeline changes with scope, but you will always know what stage the project is in.',studioLink:'Learn about the studio',thinking:title=>`Thinking about ${title.toLowerCase()}?`},
  workPage:{eyebrow:'Portfolio',title:'Selected ideas, ready for your real work.',text:'Each project below opens into a complete case-study template. When you send your portfolio images and details, we can replace these samples one by one.',replaceTitle:'Built to be replaced easily.',replaceText:'The case-study structure is ready now: overview, challenge, creative direction, services, and contact CTA. You only need to provide the real project materials later.',replaceButton:'Add a real project',similar:'Start a similar project',templateCase:'This is a template case study awaiting your real project imagery and copy.',browseCases:'Browse the other cases'},
  aboutPage:{eyebrow:'About Lumen Atelier',title:'Personal enough to listen. Professional enough to deliver.',text:'A small online studio for thoughtful visual work, with a soft spot for clear ideas, warm details, and identities that feel human.',studio:'The studio',storyTitle:'Made with care, not a production line.',story:['Lumen Atelier works across poster design, brand identity, video editing, illustration, and Live2D. The mix lets one idea move naturally across different formats while keeping the same voice.','The studio is online-first, which makes collaboration flexible for independent brands, creators, and clients in different places.'],tellUs:'Tell us about your idea',values:[['01','Clarity','A beautiful design should still make the message easy to understand.'],['02','Character','The work should feel like your story, not a copy of someone else.'],['03','Care','Small choices, useful feedback, and polished delivery all matter.']],bestTogether:'Best together',fitTitle:'A good fit for collaborative people.',fitText:'You do not need to arrive with a perfect brief. A useful starting point is simply what you are making, who it is for, what you need, and what you want people to feel.',seeServices:'See all services'},
  contactPage:{eyebrow:'Start a project',title:'Tell us what you would love to make.',text:'Fill in the short brief below. The form prepares a neat enquiry email for you; the studio email can be replaced with your real contact address when you send it to us.',whatHelps:'What helps',briefTitle:'A simple starting brief.',briefItems:['What you need','Your preferred deadline','Any useful references','Your working budget'],responseTitle:'Template response time',responseText:'1–3 working days',emailTitle:'Template email',name:'Your name',namePlaceholder:'How should we address you?',email:'Email',service:'Service',budget:'Budget',details:'Project details',detailsPlaceholder:'What are you making, who is it for, and when do you need it?',notSure:'Not sure yet',discuss:'Let’s discuss',budgets:['Under RM500','RM500–RM1,000','RM1,000–RM2,500','RM2,500+'],prepare:'Prepare enquiry',ready:'Your enquiry is ready.',readyText:'Open your email app to review it before sending.',openEmail:'Open prepared email',backHomepage:'Back to homepage',subject:'Lumen Atelier project enquiry'},
  process:{eyebrow:'From idea to delivery',title:'Our process',steps:[['01','Discover','We learn about your goals, audience, and ideas.'],['02','Create','We design, iterate, and refine with care and intention.'],['03','Deliver','We deliver polished work that is ready to shine.']]},
  banner:{eyebrow:'Have a project in mind?',title:'Let’s make something lovely.',text:'Share the idea, the format, and the feeling you want to create. We can shape the rest together.'},
  notFound:{eyebrow:'Page not found',title:'This page wandered off.',text:'The link may be old, but the homepage is right here.'},
  footer:{instagram:'Instagram · add your link',behance:'Behance · add your link',enquiry:'Project enquiry',copyright:'© 2026 Lumen Atelier. All rights reserved.'},
}

const zh = {
  locale:'zh', htmlLang:'zh-CN', pageTitle:'Lumen Atelier — 设计工作室', metaDescription:'Lumen Atelier 提供品牌视觉、海报设计、视频剪辑、插画与 Live2D 服务。', brandSubtitle:'设计工作室', brandHomeLabel:'返回 Lumen Atelier 首页', navLabel:'主导航', menuLabel:'打开或关闭导航', languageLabel:'选择网站语言',
  nav:[['首页','#/'],['作品','#/work'],['服务','#/services'],['关于','#/about'],['联系','#/contact']],
  labels:{startProject:'开始合作',backHome:'返回首页',moreAbout:'查看详情',allServices:'全部服务',allWork:'全部作品',serviceDetail:'服务详情',askService:'咨询这项服务',goodFor:'适合这些需求',deliverables:'常见交付内容',overview:'项目概览',services:'服务内容',challenge:'项目挑战',direction:'创意方向'},
  services:[
    {title:'海报设计',intro:'鲜明、清晰，让人一眼看见。',description:'为活动、推广与社交媒体打造有层次的视觉，在情绪表达与信息阅读之间取得平衡，并适配不同屏幕与版面。',goodFor:['新品与活动发布','节日促销与宣传','社交媒体系列视觉'],deliverables:['主视觉方向','完整海报设计','各平台尺寸输出','两轮细节调整']},
    {title:'品牌视觉',intro:'做出真正属于你的品牌样子。',description:'从 Logo、色彩、字体到日常应用，建立有辨识度且能长期使用的品牌视觉系统，让你的品牌拥有一致的表达。',goodFor:['新创意品牌','品牌形象更新','个人品牌与工作室'],deliverables:['创意方向','Logo 组合系统','色彩与字体规范','精简品牌指南']},
    {title:'视频剪辑',intro:'用干净的节奏讲好你的故事。',description:'根据内容、节奏与音乐整理短视频结构，搭配清晰字幕与适量动态效果，让故事更完整、更容易被看见。',goodFor:['产品短片','活动预告','创作者日常内容'],deliverables:['剪辑与节奏设计','基础动态文字','声音整理','平台规格输出']},
    {title:'插画创作',intro:'为品牌与个人画出独特温度。',description:'根据你的故事与用途定制插画，以温暖、有人情味的方式呈现，不使用千篇一律的通用素材感。',goodFor:['编辑与内容插画','品牌角色','个人定制委托'],deliverables:['草图探索','配色方向','完整插画','网页与印刷输出']},
    {title:'Live2D 制作',intro:'让角色自然、轻盈地活起来。',description:'从角色分层检查到动态与表情制作，让 Live2D 模型在画面中自然、清楚、有个性，并适合实际使用。',goodFor:['VTuber 模型','品牌吉祥物动态','直播视觉素材'],deliverables:['分层检查','建模规划','基础动态与表情','可使用的完整文件']},
  ],
  projects:[
    {category:'海报设计',title:'Bloom 创意节',year:'示例案例 · 2026',overview:'为想象中的创意节打造明亮活泼的宣传方向，以大字排版、柔和色彩与清楚的活动信息层级为核心。',challenge:'让海报远看有趣、近看清晰，同时确保日期、地点与行动信息都能被快速读取。',direction:'以淡紫色为主调，结合超大字体与模块化版式，让设计能自然延伸到限时动态、社交贴文与印刷物。',services:['美术指导','海报设计','社交媒体延展']},
    {category:'品牌视觉',title:'Nura Studio',year:'示例案例 · 2026',overview:'为现代生活方式工作室打造安静而有质感的品牌概念，将简洁字标与带触感的编辑风应用结合。',challenge:'在不过度冷淡或极简的前提下，建立平静、高级且容易被记住的品牌形象。',direction:'温暖中性色、克制的衬线细节与紧凑的文字系统，让品牌同时拥有柔软感与一致性。',services:['品牌方向','Logo 系统','品牌应用']},
    {category:'插画创作',title:'静谧时光',year:'示例案例 · 2026',overview:'以缓慢的夜晚、私人的小习惯与家的细节为主题，创作一组安静温柔的插画。',challenge:'在保留个人表达的同时，建立能持续用于不同画面的统一视觉语言。',direction:'柔软形状、克制配色与手绘小细节，让整组作品形成平静而连续的视觉节奏。',services:['概念草图','插画系统','完整绘制']},
    {category:'视频剪辑',title:'Wander — 旅行短片',year:'示例案例 · 2026',overview:'一支在安静观察与轻快剪辑之间转换的旅行短片，在变化中仍保持完整统一的情绪。',challenge:'把不同来源的素材整理成简洁、有电影感，同时适合社交媒体快速观看的故事。',direction:'节奏化转场、克制字幕与柔和色调共同维持画面的连贯感。',services:['故事剪辑','动态文字','声音与成片输出']},
    {category:'Live2D',title:'Liora — VTuber 模型',year:'示例案例 · 2026',overview:'以细腻表情、清楚轮廓变化与亲切的镜头表现为重点，打造自然耐看的角色动态示例。',challenge:'让角色拥有足够的生命力，同时不过度晃动，不干扰说话与直播内容。',direction:'轻微呼吸、平衡的头部角度与精简实用的表情组合，构成自然的日常表现。',services:['分层规划','基础建模','表情设置']},
  ],
  home:{eyebrow:'独立设计工作室',heroTitle:['让想法，','清晰','被看见。'],heroText:'从品牌、海报、动态到插画，为值得被注意的故事，做出认真又有温度的视觉。',viewWork:'查看精选作品',exploreServices:'了解服务',whatWeDo:'我们能做什么',servicesTitle:'服务项目',viewServices:'查看全部服务',meetStudio:'认识工作室',studioTitle:['小小工作室，','装着明亮想法。'],studioText:['Lumen Atelier 是一间小型多领域线上设计工作室，为创意品牌、个人品牌、主播与所有有趣的想法提供视觉设计。','我们把策略、叙事与设计细节放在一起，做出真正能与人连接、也让人记得住的作品。'],moreAboutUs:'了解我们',notes:[['认真做','有意义的设计'],['草图','探索','细化']],firstLook:'先看一眼',selectedWork:'精选作品',viewAllWork:'查看全部作品',templateNote:'目前展示的是完整案例模板；之后可以直接替换成你的真实作品，不需要重做网站结构。'},
  servicesPage:{eyebrow:'服务项目',title:'围绕你的故事，提供刚刚好的创意支持。',text:'从下面选择一个方向。每项服务都有独立详情、交付内容，也能随时返回首页。',flexible:'灵活组合',moreThanOne:'需要不止一项服务？',packageText:'品牌视觉可以延伸成海报，插画也可以继续做成动态；Live2D 模型可能还需要发布视觉。告诉我们项目真正需要什么，我们可以替你组合成完整方案。',packageButton:'定制合作方案',howItWorks:'合作方式',stepsTitle:'步骤清楚，每个决定都有理由。',stepsText:'我们会先了解你的目标与参考方向，再确认整体视觉，最后逐步细化成品。实际时间会依项目规模调整，但你会一直知道项目进行到哪一个阶段。',studioLink:'了解工作室',thinking:title=>`正在考虑${title}吗？`},
  workPage:{eyebrow:'作品集',title:'精选创意，等待换上你的真实作品。',text:'下面每个项目都能打开完整案例详情。你之后把作品图片与资料发来，我们就能逐一替换这些示例。',replaceTitle:'结构已经准备好，替换很简单。',replaceText:'案例页面已经包含项目概览、挑战、创意方向、服务内容与联系入口；之后只需要补上你的真实图片与文字。',replaceButton:'加入真实作品',similar:'开始类似项目',templateCase:'这是等待替换成真实图片与文案的案例模板。',browseCases:'浏览其他案例'},
  aboutPage:{eyebrow:'关于 Lumen Atelier',title:'足够贴近，认真倾听；也足够专业，把作品做好。',text:'一间专注于细腻视觉的小型线上工作室，喜欢清楚的想法、温暖的细节，以及真正有人情味的品牌。',studio:'关于工作室',storyTitle:'用心制作，不走流水线。',story:['Lumen Atelier 提供海报设计、品牌视觉、视频剪辑、插画与 Live2D。多领域的工作方式，让同一个想法可以延伸到不同形式，同时保持一致的声音。','工作室以线上合作为主，让独立品牌、创作者与不同地区的客户都能更灵活地一起完成项目。'],tellUs:'告诉我们你的想法',values:[['01','清晰','好看的设计，也应该让重要信息一眼就能理解。'],['02','个性','作品应该像你的故事，而不是复制另一个人的样子。'],['03','用心','每个小选择、实用的沟通与完整交付，都同样重要。']],bestTogether:'适合彼此的合作',fitTitle:'适合愿意一起沟通与探索的人。',fitText:'你不需要带着一份完美企划来。只要先告诉我们：你在做什么、想给谁看、需要什么，以及希望别人感受到什么，就已经是很好的开始。',seeServices:'查看全部服务'},
  contactPage:{eyebrow:'开始合作',title:'告诉我们，你最想做出什么。',text:'填写下面的简单需求表，网站会替你整理成一封询问信；之后你把真实联系方式给我们，就能换成正式工作室邮箱。',whatHelps:'这些资料会很有帮助',briefTitle:'从简单的需求开始。',briefItems:['你需要制作什么','希望完成的时间','有帮助的参考图','预计合作预算'],responseTitle:'示例回复时间',responseText:'1–3 个工作日',emailTitle:'示例邮箱',name:'你的称呼',namePlaceholder:'我们应该怎么称呼你？',email:'电子邮箱',service:'需要的服务',budget:'预算范围',details:'项目详情',detailsPlaceholder:'你想做什么、是为谁制作，以及希望什么时候完成？',notSure:'还不确定',discuss:'可以再讨论',budgets:['RM500 以下','RM500–RM1,000','RM1,000–RM2,500','RM2,500 以上'],prepare:'整理询问信',ready:'你的询问信已经准备好了。',readyText:'打开邮箱后，可以先检查内容再发送。',openEmail:'打开准备好的邮件',backHomepage:'返回首页',subject:'Lumen Atelier 项目咨询'},
  process:{eyebrow:'从想法到交付',title:'合作流程',steps:[['01','了解','认识你的目标、受众与想法。'],['02','创作','设计、沟通、调整，把方向一步步细化。'],['03','交付','整理并交付可以直接使用的完整作品。']]},
  banner:{eyebrow:'心里已经有个项目了吗？',title:'一起做点好看的东西吧。',text:'告诉我们你的想法、需要的形式，以及希望作品带来的感觉；剩下的部分，我们可以一起慢慢整理。'},
  notFound:{eyebrow:'找不到页面',title:'这个页面好像走丢了。',text:'链接可能已经改变，不过首页一直都在这里。'},
  footer:{instagram:'Instagram · 等待加入链接',behance:'Behance · 等待加入链接',enquiry:'项目咨询',copyright:'© 2026 Lumen Atelier。保留所有权利。'},
}

export const content = { en, zh }
